2017-10-26 20:19:55 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=3 from 2017-10-14 03:02:39.754889)
2017-10-26 20:20:07 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds.
2017-10-26 20:38:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:30.555637')]
2017-10-26 20:38:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:30.555637')]. (retrying in 3 seconds)
2017-10-26 20:38:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:33.600557')]
2017-10-26 20:38:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:33.600557')]. (retrying in 3 seconds)
2017-10-26 20:38:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:36.634638')]
2017-10-26 20:38:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:36.634638')]. (retrying in 3 seconds)
2017-10-26 20:38:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:39.667586')]
2017-10-26 20:38:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:39.667586')]. (retrying in 3 seconds)
2017-10-26 20:38:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:42.702503')]
2017-10-26 20:38:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:42.702503')]. (retrying in 3 seconds)
2017-10-26 20:38:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:45.732664')]
2017-10-26 20:38:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:45.732664')]. (retrying in 3 seconds)
2017-10-26 20:38:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:48.763231')]
2017-10-26 20:38:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:48.763231')]. (retrying in 3 seconds)
2017-10-26 20:38:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:51.795084')]
2017-10-26 20:38:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:51.795084')]. (retrying in 3 seconds)
2017-10-26 20:38:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:54.824420')]
2017-10-26 20:38:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.53, "azimuth": 279.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:38:30.505664', '2017-10-27 03:38:54.824420')]. (retrying in 3 seconds)
2017-10-26 20:38:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:57.858000')]
2017-10-26 20:38:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 279.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:38:30.505664+00:00"}}', 'LOCAL', '2017-10-27 03:38:30.505813', '2017-10-27 03:38:57.858000')]. (retrying in 3 seconds)
2017-10-26 20:38:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:39:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:30.527162')]
2017-10-26 20:39:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:30.527162')]. (retrying in 3 seconds)
2017-10-26 20:39:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:33.556347')]
2017-10-26 20:39:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:33.556347')]. (retrying in 3 seconds)
2017-10-26 20:39:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:36.589091')]
2017-10-26 20:39:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:36.589091')]. (retrying in 3 seconds)
2017-10-26 20:39:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:39.617941')]
2017-10-26 20:39:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:39.617941')]. (retrying in 3 seconds)
2017-10-26 20:39:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:42.648265')]
2017-10-26 20:39:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:42.648265')]. (retrying in 3 seconds)
2017-10-26 20:39:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:45.683409')]
2017-10-26 20:39:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:45.683409')]. (retrying in 3 seconds)
2017-10-26 20:39:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:48.715402')]
2017-10-26 20:39:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:48.715402')]. (retrying in 3 seconds)
2017-10-26 20:39:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:51.747400')]
2017-10-26 20:39:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:51.747400')]. (retrying in 3 seconds)
2017-10-26 20:39:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:54.776895')]
2017-10-26 20:39:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.02, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:39:30.504269+00:00"}}', 'LOCAL', '2017-10-27 03:39:30.504412', '2017-10-27 03:39:54.776895')]. (retrying in 3 seconds)
2017-10-26 20:39:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:57.806583')]
2017-10-26 20:39:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.74, "azimuth": 280.02, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:39:30.504269', '2017-10-27 03:39:57.806583')]. (retrying in 3 seconds)
2017-10-26 20:39:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:40:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:30.525254')]
2017-10-26 20:40:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:30.525254')]. (retrying in 3 seconds)
2017-10-26 20:40:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:33.564849')]
2017-10-26 20:40:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:33.564849')]. (retrying in 3 seconds)
2017-10-26 20:40:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.94, "azimuth": 280.19, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:40:30.504149', '2017-10-27 03:40:36.600161')]
2017-10-26 20:40:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -37.94, "azimuth": 280.19, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:40:30.504149', '2017-10-27 03:40:36.600161')]. (retrying in 3 seconds)
2017-10-26 20:40:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:39.635313')]
2017-10-26 20:40:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:39.635313')]. (retrying in 3 seconds)
2017-10-26 20:40:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:42.674266')]
2017-10-26 20:40:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:42.674266')]. (retrying in 3 seconds)
2017-10-26 20:40:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:45.715503')]
2017-10-26 20:40:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:45.715503')]. (retrying in 3 seconds)
2017-10-26 20:40:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:48.753458')]
2017-10-26 20:40:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:48.753458')]. (retrying in 3 seconds)
2017-10-26 20:40:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:51.792174')]
2017-10-26 20:40:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:51.792174')]. (retrying in 3 seconds)
2017-10-26 20:40:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:54.829294')]
2017-10-26 20:40:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:54.829294')]. (retrying in 3 seconds)
2017-10-26 20:40:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:57.867547')]
2017-10-26 20:40:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.19, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:40:30.504149+00:00"}}', 'LOCAL', '2017-10-27 03:40:30.504287', '2017-10-27 03:40:57.867547')]. (retrying in 3 seconds)
2017-10-26 20:40:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:41:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:30.522070')]
2017-10-26 20:41:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:30.522070')]. (retrying in 3 seconds)
2017-10-26 20:41:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:33.555646')]
2017-10-26 20:41:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:33.555646')]. (retrying in 3 seconds)
2017-10-26 20:41:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.15, "azimuth": 280.36, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:41:30.504356', '2017-10-27 03:41:36.589885')]
2017-10-26 20:41:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.15, "azimuth": 280.36, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:41:30.504356', '2017-10-27 03:41:36.589885')]. (retrying in 3 seconds)
2017-10-26 20:41:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:39.624923')]
2017-10-26 20:41:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:39.624923')]. (retrying in 3 seconds)
2017-10-26 20:41:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.15, "azimuth": 280.36, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:41:30.504356', '2017-10-27 03:41:42.664979')]
2017-10-26 20:41:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.15, "azimuth": 280.36, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:41:30.504356', '2017-10-27 03:41:42.664979')]. (retrying in 3 seconds)
2017-10-26 20:41:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:45.702636')]
2017-10-26 20:41:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:45.702636')]. (retrying in 3 seconds)
2017-10-26 20:41:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:48.735964')]
2017-10-26 20:41:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:48.735964')]. (retrying in 3 seconds)
2017-10-26 20:41:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:51.765714')]
2017-10-26 20:41:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:51.765714')]. (retrying in 3 seconds)
2017-10-26 20:41:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:54.799304')]
2017-10-26 20:41:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:54.799304')]. (retrying in 3 seconds)
2017-10-26 20:41:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:57.847800')]
2017-10-26 20:41:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.36, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:41:30.504356+00:00"}}', 'LOCAL', '2017-10-27 03:41:30.504497', '2017-10-27 03:41:57.847800')]. (retrying in 3 seconds)
2017-10-26 20:41:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:42:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:30.532579')]
2017-10-26 20:42:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:30.532579')]. (retrying in 3 seconds)
2017-10-26 20:42:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:33.571576')]
2017-10-26 20:42:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:33.571576')]. (retrying in 3 seconds)
2017-10-26 20:42:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:36.602763')]
2017-10-26 20:42:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:36.602763')]. (retrying in 3 seconds)
2017-10-26 20:42:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:39.632614')]
2017-10-26 20:42:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:39.632614')]. (retrying in 3 seconds)
2017-10-26 20:42:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:42.664611')]
2017-10-26 20:42:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:42.664611')]. (retrying in 3 seconds)
2017-10-26 20:42:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:45.696838')]
2017-10-26 20:42:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:45.696838')]. (retrying in 3 seconds)
2017-10-26 20:42:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:48.738087')]
2017-10-26 20:42:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:48.738087')]. (retrying in 3 seconds)
2017-10-26 20:42:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:51.769613')]
2017-10-26 20:42:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:51.769613')]. (retrying in 3 seconds)
2017-10-26 20:42:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:54.802480')]
2017-10-26 20:42:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.52, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:42:30.504960+00:00"}}', 'LOCAL', '2017-10-27 03:42:30.505105', '2017-10-27 03:42:54.802480')]. (retrying in 3 seconds)
2017-10-26 20:42:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:57.836311')]
2017-10-26 20:42:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.36, "azimuth": 280.52, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:42:30.504960', '2017-10-27 03:42:57.836311')]. (retrying in 3 seconds)
2017-10-26 20:42:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:43:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:30.525148')]
2017-10-26 20:43:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:30.525148')]. (retrying in 3 seconds)
2017-10-26 20:43:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:33.559366')]
2017-10-26 20:43:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:33.559366')]. (retrying in 3 seconds)
2017-10-26 20:43:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:36.592565')]
2017-10-26 20:43:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:36.592565')]. (retrying in 3 seconds)
2017-10-26 20:43:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:39.627101')]
2017-10-26 20:43:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:39.627101')]. (retrying in 3 seconds)
2017-10-26 20:43:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:42.657754')]
2017-10-26 20:43:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:42.657754')]. (retrying in 3 seconds)
2017-10-26 20:43:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:45.696756')]
2017-10-26 20:43:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:45.696756')]. (retrying in 3 seconds)
2017-10-26 20:43:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:48.733928')]
2017-10-26 20:43:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:48.733928')]. (retrying in 3 seconds)
2017-10-26 20:43:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:51.767874')]
2017-10-26 20:43:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.56, "azimuth": 280.69, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:43:30.505353', '2017-10-27 03:43:51.767874')]. (retrying in 3 seconds)
2017-10-26 20:43:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:54.802189')]
2017-10-26 20:43:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:54.802189')]. (retrying in 3 seconds)
2017-10-26 20:43:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:57.840509')]
2017-10-26 20:43:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.69, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:43:30.505353+00:00"}}', 'LOCAL', '2017-10-27 03:43:30.505496', '2017-10-27 03:43:57.840509')]. (retrying in 3 seconds)
2017-10-26 20:43:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:44:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:30.523507')]
2017-10-26 20:44:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:30.523507')]. (retrying in 3 seconds)
2017-10-26 20:44:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:33.556962')]
2017-10-26 20:44:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:33.556962')]. (retrying in 3 seconds)
2017-10-26 20:44:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:36.590513')]
2017-10-26 20:44:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:36.590513')]. (retrying in 3 seconds)
2017-10-26 20:44:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:39.621064')]
2017-10-26 20:44:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:39.621064')]. (retrying in 3 seconds)
2017-10-26 20:44:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:42.653571')]
2017-10-26 20:44:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:42.653571')]. (retrying in 3 seconds)
2017-10-26 20:44:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:45.685391')]
2017-10-26 20:44:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:45.685391')]. (retrying in 3 seconds)
2017-10-26 20:44:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:48.719523')]
2017-10-26 20:44:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.77, "azimuth": 280.86, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:44:30.504375', '2017-10-27 03:44:48.719523')]. (retrying in 3 seconds)
2017-10-26 20:44:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:51.753902')]
2017-10-26 20:44:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:51.753902')]. (retrying in 3 seconds)
2017-10-26 20:44:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:54.783884')]
2017-10-26 20:44:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:54.783884')]. (retrying in 3 seconds)
2017-10-26 20:44:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:57.815290')]
2017-10-26 20:44:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 280.86, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:44:30.504375+00:00"}}', 'LOCAL', '2017-10-27 03:44:30.504516', '2017-10-27 03:44:57.815290')]. (retrying in 3 seconds)
2017-10-26 20:44:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-26 20:45:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:30.522329')]
2017-10-26 20:45:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:30.522329')]. (retrying in 3 seconds)
2017-10-26 20:45:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:33.554001')]
2017-10-26 20:45:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:33.554001')]. (retrying in 3 seconds)
2017-10-26 20:45:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:36.588875')]
2017-10-26 20:45:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:36.588875')]. (retrying in 3 seconds)
2017-10-26 20:45:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:39.623054')]
2017-10-26 20:45:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:39.623054')]. (retrying in 3 seconds)
2017-10-26 20:45:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:42.654503')]
2017-10-26 20:45:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:42.654503')]. (retrying in 3 seconds)
2017-10-26 20:45:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:45.684690')]
2017-10-26 20:45:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:45.684690')]. (retrying in 3 seconds)
2017-10-26 20:45:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:48.731488')]
2017-10-26 20:45:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:48.731488')]. (retrying in 3 seconds)
2017-10-26 20:45:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:51.765845')]
2017-10-26 20:45:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:51.765845')]. (retrying in 3 seconds)
2017-10-26 20:45:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:54.803567')]
2017-10-26 20:45:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_dawn": "2017-10-27T13:16:26+00:00", "next_dusk": "2017-10-28T01:06:40+00:00", "next_midnight": "2017-10-27T07:11:29+00:00", "next_noon": "2017 ... (27 characters truncated) ... xt_rising": "2017-10-27T13:41:53+00:00", "next_setting": "2017-10-28T00:41:14+00:00", "elevation": -38.97, "azimuth": 281.03, "friendly_name": "Sun"}', None, '2017-10-27 03:19:57.616700', '2017-10-27 03:45:30.505422', '2017-10-27 03:45:54.803567')]. (retrying in 3 seconds)
2017-10-26 20:45:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:57.838129')]
2017-10-26 20:45:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T13:16:26+00:00", "ne ... (746 characters truncated) ...  "azimuth": 281.03, "friendly_name": "Sun"}, "last_changed": "2017-10-27T03:19:57.616700+00:00", "last_updated": "2017-10-27T03:45:30.505422+00:00"}}', 'LOCAL', '2017-10-27 03:45:30.505561', '2017-10-27 03:45:57.838129')]. (retrying in 3 seconds)
2017-10-26 20:45:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
